const dialog=document.querySelector('#order-dialog');
const item=document.querySelector('#item');
const validItems=[...item.options].map(o=>o.value);
function startOrder(name){if(!validItems.includes(name))throw new Error('不支援的作品款式');item.value=name;document.querySelector('#result').hidden=true;document.querySelector('#status').textContent='';if(!dialog.open)dialog.showModal();return {item:name,status:'draft_opened'};}
document.querySelectorAll('[data-order]').forEach(b=>b.addEventListener('click',()=>startOrder(b.dataset.order)));
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.querySelector('#order-form').addEventListener('submit',e=>{e.preventDefault();const quantity=Number(document.querySelector('#quantity').value);if(!Number.isInteger(quantity)||quantity<1||quantity>999)return;document.querySelector('#order-text').value=['您好，我想詢問米亞紙意手作的作品：','款式：'+item.value,'數量：'+quantity,'希望收到日期：'+(document.querySelector('#date').value||'待討論'),'需求：'+(document.querySelector('#note').value.trim()||'想進一步討論'),'請協助確認報價、製作時間與交付方式，謝謝。'].join('\n');document.querySelector('#result').hidden=false;document.querySelector('#status').textContent='';document.querySelector('#order-text').focus();});
document.querySelector('#copy').addEventListener('click',async()=>{const t=document.querySelector('#order-text');try{await navigator.clipboard.writeText(t.value);document.querySelector('#status').textContent='已複製，可貼到你與米亞的聯絡對話中。';}catch{t.focus();t.select();document.querySelector('#status').textContent='請長按或使用 Ctrl+C 複製選取的需求。';}});
document.querySelector('#year').textContent=new Date().getFullYear();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'start_miya_order_draft',title:'整理米亞訂製需求',description:'開啟訂製需求草稿，不會送出訂單或付款。',inputSchema:{type:'object',properties:{item:{type:'string',enum:validItems}},required:['item'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.item!=='string'||Object.keys(input).some(k=>k!=='item'))throw new Error('請提供有效的作品款式');return startOrder(input.item);}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
